package com.gome.statistic.infrastructure.mysql.entity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class HaiyanUserAnalyseEntity implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.218+08:00", comments="Source field: haiyan_user_analyse.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.quota")
    private String quota;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.number")
    private String number;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.start_time")
    private Date startTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.226+08:00", comments="Source field: haiyan_user_analyse.end_time")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table haiyan_user_analyse
     *
     * @mbg.generated Mon Sep 23 15:13:50 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.224+08:00", comments="Source field: haiyan_user_analyse.id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_user_analyse
     *
     * @mbg.generated Mon Sep 23 15:13:50 CST 2019
     */
    public HaiyanUserAnalyseEntity withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.quota")
    public String getQuota() {
        return quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_user_analyse
     *
     * @mbg.generated Mon Sep 23 15:13:50 CST 2019
     */
    public HaiyanUserAnalyseEntity withQuota(String quota) {
        this.setQuota(quota);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.quota")
    public void setQuota(String quota) {
        this.quota = quota == null ? null : quota.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.number")
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_user_analyse
     *
     * @mbg.generated Mon Sep 23 15:13:50 CST 2019
     */
    public HaiyanUserAnalyseEntity withNumber(String number) {
        this.setNumber(number);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.number")
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.start_time")
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_user_analyse
     *
     * @mbg.generated Mon Sep 23 15:13:50 CST 2019
     */
    public HaiyanUserAnalyseEntity withStartTime(Date startTime) {
        this.setStartTime(startTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.225+08:00", comments="Source field: haiyan_user_analyse.start_time")
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.226+08:00", comments="Source field: haiyan_user_analyse.end_time")
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_user_analyse
     *
     * @mbg.generated Mon Sep 23 15:13:50 CST 2019
     */
    public HaiyanUserAnalyseEntity withEndTime(Date endTime) {
        this.setEndTime(endTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-09-23T15:13:50.226+08:00", comments="Source field: haiyan_user_analyse.end_time")
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haiyan_user_analyse
     *
     * @mbg.generated Mon Sep 23 15:13:50 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", quota=").append(quota);
        sb.append(", number=").append(number);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}